In [2]:
import pandas as pd
import numpy as np

In [26]:
golub_cl = pd.read_csv("/Users/stephenandrews/Downloads/MIT Schoolwork/Spring 2025/6.3730/6373Pset1/data_and_materials/golub_data/golub_cl.csv")
golub_gnames = pd.read_csv("/Users/stephenandrews/Downloads/MIT Schoolwork/Spring 2025/6.3730/6373Pset1/data_and_materials/golub_data/golub_gnames.csv")
golub = pd.read_csv("/Users/stephenandrews/Downloads/MIT Schoolwork/Spring 2025/6.3730/6373Pset1/data_and_materials/golub_data/golub.csv")


print(golub_cl.head())
print('------------')
print(golub_gnames.head())
print('------------')
print(golub.head())

golub_cl_np = golub_cl.to_numpy()
golub_gnames_np = golub_gnames.to_numpy()
golub_np = golub.to_numpy()[:, 1:]


   Unnamed: 0  x
0           1  0
1           2  0
2           3  0
3           4  0
4           5  0
------------
   Unnamed: 0  V1                                                V2  \
0           1  36  AFFX-HUMISGF3A/M97935_MA_at (endogenous control)   
1           2  37  AFFX-HUMISGF3A/M97935_MB_at (endogenous control)   
2           3  38   AFFX-HUMISGF3A/M97935_3_at (endogenous control)   
3           4  39      AFFX-HUMRGE/M10098_5_at (endogenous control)   
4           5  40      AFFX-HUMRGE/M10098_M_at (endogenous control)   

                            V3  
0  AFFX-HUMISGF3A/M97935_MA_at  
1  AFFX-HUMISGF3A/M97935_MB_at  
2   AFFX-HUMISGF3A/M97935_3_at  
3      AFFX-HUMRGE/M10098_5_at  
4      AFFX-HUMRGE/M10098_M_at  
------------
   Unnamed: 0       V1       V2       V3       V4       V5       V6       V7  \
0           1 -1.45769 -1.39420 -1.42779 -1.40715 -1.42668 -1.21719 -1.37386   
1           2 -0.75161 -1.26278 -0.09052 -0.99596 -1.24245 -0.69242 -1.37386   
2      

In [ ]:
#Getting Means for ALL vs AML for each gene

AML_mask = (golub_cl_np[:, 1]).astype(bool) # True for patients with AML, False otherwise

AML_array = golub_np[:, AML_mask]
mu_M = np.mean(AML_array, axis=1)

ALL_array = golub_np[:, ~AML_mask]
mu_L = np.mean(ALL_array, axis=1)


[[-1.43337 -1.08902 -1.29865 ... -0.75919  0.84905 -0.66465]
 [-1.18065 -1.08902 -1.05094 ... -0.71792  0.45127 -0.45804]
 [ 0.26624 -0.43377 -0.10823 ...  0.24347  0.90774  0.46509]
 ...
 [ 0.65067 -0.13281  0.35006 ...  0.72762  1.10466  1.1699 ]
 [-0.49941 -1.08902 -0.62199 ... -0.37737 -0.39063  0.33975]
 [ 0.28711  1.90481 -0.2165  ... -0.65113  1.62964  1.60048]]
(3051, 11)
[-0.77924727 -0.69194182  0.24663909 ...  0.68216455 -0.35427636
  0.41675636] (3051,)
